In [97]:
import torch

In [98]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat
from scipy.signal import butter, lfilter , filtfilt
import pandas as pd
import scipy as sp
import os
import sys
import seaborn as sb 
from matplotlib import cm

import pickle


# Load the Dic

In [99]:

class DfSubject:
    def __init__(self, elec_i, muscle_i):
        self.Elec_config=list_elecs[elec_i]
        self.List_elecs=list_elecs
        self.Muscle_or_other=list_muscle_or_other_elec_i[muscle_i]
        self.List_muscle_or_other=list_muscle_or_other_elec_i
        self.Trial_number= df_subject_no_empty[(df_subject_no_empty["Elec_config"]==self.Elec_config)& (df_subject_no_empty["Muscle_or_other"]== self.Muscle_or_other)]["Trial_number"]
        self.Trial_number=[int(i) for i in self.Trial_number] #save as int
        self.Raw= df_subject_no_empty[(df_subject_no_empty["Elec_config"]==self.Elec_config)& (df_subject_no_empty["Muscle_or_other"]== self.Muscle_or_other)]["Raw"]
        self.Raw.index=self.Trial_number
        self.Time_points= df_subject_no_empty[(df_subject_no_empty["Elec_config"]==self.Elec_config)& (df_subject_no_empty["Muscle_or_other"]== self.Muscle_or_other)]["Time_points"]
        self.Time_points.index=self.Trial_number
        self.Amplitudes= df_subject_no_empty[(df_subject_no_empty["Elec_config"]==self.Elec_config)& (df_subject_no_empty["Muscle_or_other"]== self.Muscle_or_other)]["Amplitudes"]
        self.Amplitudes.index=self.Trial_number
        self.TS_arts_1="$"
        
        # self.TS_arts_1.index=self.Trial_number
        self.Time_points_arts_1=-1
        self.TS_arts_2="$"
        self.Time_points_arts_2=-1
        self.TS_arts_3="$"
        self.Time_points_arts_3=-1


# Goal is to chose an electrode and a muscle and see all the trials and the corrected data        
#  Access data the following way: pData["_3_5"].Raw[19] #prints the raw data from trial 19

In [100]:
### retrieve  dfSubject structured as pData  #
#run the structure of the data before opening the pickle (wihtout creating an object)
# command pData["_0_0"].Trial_number=0
import pickle
run=1
if run == 1:  

    with open('Class2_Dump.pkl', 'rb') as handle:
        pData = pickle.load(handle)


# Make a tensor (include all data in one tensor)

Build the tensor matrix with the raw data.
Time X Electrodes X Muscles X Amplitudes (Stimulation) X Muscle activity (EMG)
Right now it's a table (16410(=all the trials) x 14440(TP+AMp+RAw(1404)+Elec(20)+Muscle(15)))
Since the data doesn't have the same dimension I wouldn't know how to stack? eg tensor.shape(5, 16410, ?)
->Once I have the specified nr. of columns I could adapt the different lists and use tensor.reshape(5,16410, ?)


In [101]:
device =  "cuda" if torch.cuda.is_available() else "cpu"

### Extract list

The 5 dimensions that should be included in the tensor 
    
    elecs_to_nr
    muscles_to_nr 
    raw_data_to_matrix, 
    amplitudes_to_list, 
    time_points_to_list

In [102]:

## save Amplitudes in a list ##
amplitudes_to_list=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                amplitudes_to_list.append(pData[f'_{elec_i}_{muscle_i}'].Amplitudes[trial])
                

print(len(amplitudes_to_list)) #16410

16410


In [202]:

## save raw_data in a list ##
#with append() in order to save lists of lists
raw_data_to_matrix=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                raw_data_to_matrix.append(pData[f'_{elec_i}_{muscle_i}'].Raw[trial])
               

print(len(raw_data_to_matrix))
print((raw_data_to_matrix[0].dtype)) #float64
# print((raw_data_to_matrix[0:10].dtype)) #error


11802
float64


In [104]:

## save the Time_points in a list ##
time_points_to_list=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                time_points_to_list.append(pData[f'_{elec_i}_{muscle_i}'].Time_points[trial])
                

print(len(time_points_to_list)) #16410


16410


In [105]:
## save Muscles in a list ##
muscles_to_list=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                muscles_to_list.append(pData[f'_{elec_i}_{muscle_i}'].Muscle_or_other)
                

print(len(muscles_to_list)) #16410
print(muscles_to_list[0:10])

16410
['LST', 'LST', 'LST', 'LST', 'LST', 'LST', 'LST', 'LST', 'LST', 'LST']


In [106]:
## save Elecs in a list ##
elecs_to_list=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                elecs_to_list.append(pData[f'_{elec_i}_{muscle_i}'].Elec_config)
                

print(len(elecs_to_list)) #16410
print(elecs_to_list[0:10])

16410
['Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_']


#### Use Hot encoder to convert from str to number
for muscles and elecs (since the data is str and for the tensor can only have one data type)

In [107]:
# Use hot encoder to convert elecs to nrs
import pandas as pd
elecs_to_nr=pd.get_dummies(
    np.array(elecs_to_list), 
    prefix=None, 
    prefix_sep='_', 
    dummy_na=False, 
    columns=None, 
    sparse=False, 
    drop_first=False, 
    dtype=None
)

In [108]:
# Use hot encoder to convert muscles to nrs
import pandas as pd
muscles_to_nr=pd.get_dummies(
    np.array(muscles_to_list), 
    prefix=None, 
    prefix_sep='_', 
    dummy_na=False, 
    columns=None, 
    sparse=False, 
    drop_first=False, 
    dtype=None
)

In [109]:
# Use hot encoder to convert elecs to nrs
import pandas as pd
elecs_to_nr=pd.get_dummies(
    np.array(elecs_to_list), 
    prefix=None, 
    prefix_sep='_', 
    dummy_na=False, 
    columns=None, 
    sparse=False, 
    drop_first=False, 
    dtype=None
)

### Save the lists  in one tensor

elecs_to_nr, # pandas df
muscles_to_nr # pandas df
raw_data_to_matrix, 
amplitudes_to_list, 
time_points_to_list

#### concatenate data to one df

In [110]:
##### concat muscles and elecs ###
muscles_to_nr.reset_index(drop=True, inplace=True)
elecs_to_nr.reset_index(drop=True, inplace=True)
muscles_to_nr.index = elecs_to_nr.index
muscles_and_elecs=pd.concat([muscles_to_nr, elecs_to_nr], axis=1)

##### add the raw data
raw_data_to_df = pd.DataFrame(raw_data_to_matrix) #convert to a pandas df
if len(raw_data_to_df.iloc[0])!=len((raw_data_to_matrix[0])): #get rid of nan column
    raw_data_to_df=raw_data_to_df.iloc[: , :-1]
raw_data_to_df.reset_index(drop=True, inplace=True)
muscles_and_elecs.reset_index(drop=True, inplace=True)
muscles_and_elecs.index = raw_data_to_df.index
muscles_and_elecs_and_raw=pd.concat([muscles_and_elecs, raw_data_to_df], axis=1)

##### add the amplitude
amplitudes_to_df=pd.DataFrame(amplitudes_to_list) #convert to a pandas df
amplitudes_to_df.reset_index(drop=True, inplace=True)
muscles_and_elecs_and_raw.reset_index(drop=True, inplace=True)
muscles_and_elecs_and_raw.index = amplitudes_to_df.index
muscles_and_elecs_and_raw_and_amplitudes=pd.concat([muscles_and_elecs_and_raw, amplitudes_to_df], axis=1)

##### add time_points
time_points_to_df=pd.DataFrame(time_points_to_list) #convert to a pandas df
time_points_to_df.reset_index(drop=True, inplace=True)
muscles_and_elecs_and_raw_and_amplitudes.reset_index(drop=True, inplace=True)
muscles_and_elecs_and_raw_and_amplitudes.index = time_points_to_df.index
muscles_and_elecs_and_raw_and_amplitudes_and_time_points=pd.concat([muscles_and_elecs_and_raw_and_amplitudes, time_points_to_df], axis=1)
# print(pd.concat([muscles_and_elecs_and_raw_and_amplitudes[0:10], time_points_to_df[0:10]], axis=1))


#### convert df to tensor

In [111]:
#### Convert df to tensor ###
# determine the supported device
#with correction of nan values
def get_device():
    if torch.cuda.is_available():
        device = torch.device('cuda:0')
    else:
        device = torch.device('cpu') # don't have GPU 
    return device

# convert a df to tensor to be used in pytorch
def df_to_tensor(muscles_and_elecs_and_raw_and_amplitudes_and_time_points):
    device = get_device()
    return torch.from_numpy(muscles_and_elecs_and_raw_and_amplitudes_and_time_points.values).float().to(device)

df_tensor = df_to_tensor(muscles_and_elecs_and_raw_and_amplitudes_and_time_points)
# series_tensor = df_to_tensor(series)
print(df_tensor[0:10])
print(df_tensor[0:10].shape)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 9.0098e-01, 1.5000e+00,
         1.4030e+03],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 9.0098e-01, 1.5000e+00,
         1.4030e+03],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 9.0098e-01, 1.5000e+00,
         1.4030e+03],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 9.0098e-01, 1.7000e+00,
         1.4030e+03],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 9.0098e-01, 1.7000e+00,
         1.4030e+03],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 9.0098e-01, 1.7000e+00,
         1.4030e+03]])
torch.Size([10, 1440])


# Make a tensor for each "dimension"

## For Amplitude and Time_points (lists)

In [112]:

## save Amplitudes in a list ##
amplitudes_to_list=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                amplitudes_to_list.append(pData[f'_{elec_i}_{muscle_i}'].Amplitudes[trial])
                

print(len(amplitudes_to_list)) #16410
amplitudes_to_tensor = torch.tensor(amplitudes_to_list, dtype=torch.float32, device=device, requires_grad=True)

16410


In [113]:

## save the Time_points in a list ##
time_points_to_list=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                time_points_to_list.append(pData[f'_{elec_i}_{muscle_i}'].Time_points[trial])
                

print(len(time_points_to_list)) #16410
time_points_to_tensor = torch.tensor(time_points_to_list, dtype=torch.float32, device=device, requires_grad=True)

16410


## For 2d data

### Muscles

In [114]:
## save Muscles in a list ##
muscles_to_list=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                muscles_to_list.append(pData[f'_{elec_i}_{muscle_i}'].Muscle_or_other)
                

print(len(muscles_to_list)) #16410
print(muscles_to_list[0:10])

16410
['LST', 'LST', 'LST', 'LST', 'LST', 'LST', 'LST', 'LST', 'LST', 'LST']


In [115]:
# Use hot encoder to convert muscles to nrs
import pandas as pd
muscles_to_nr=pd.get_dummies(
    np.array(muscles_to_list), 
    prefix=None, 
    prefix_sep='_', 
    dummy_na=False, 
    columns=None, 
    sparse=False, 
    drop_first=False, 
    dtype=None
)

In [116]:
#### Convert df to tensor ###

def get_device():
    if torch.cuda.is_available():
        device = torch.device('cuda:0')
    else:
        device = torch.device('cpu') # don't have GPU 
    return device

# convert a df to tensor to be used in pytorch
def df_to_tensor(muscles_to_nr):
    device = get_device()
    return torch.from_numpy(muscles_to_nr.values).float().to(device)

muscles_to_tensor = df_to_tensor(muscles_to_nr)
# series_tensor = df_to_tensor(series)
print(muscles_to_tensor[0:10])
print(muscles_to_tensor[0:10].shape)

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
torch.Size([10, 15])


### Elecs

In [117]:
## save Elecs in a list ##
elecs_to_list=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                elecs_to_list.append(pData[f'_{elec_i}_{muscle_i}'].Elec_config)
                

print(len(elecs_to_list)) #16410
print(elecs_to_list[0:10])

16410
['Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_', 'Elec01_']


In [118]:
# Use hot encoder to convert elecs to nrs
import pandas as pd
elecs_to_nr=pd.get_dummies(
    np.array(elecs_to_list), 
    prefix=None, 
    prefix_sep='_', 
    dummy_na=False, 
    columns=None, 
    sparse=False, 
    drop_first=False, 
    dtype=None
)

In [119]:
#### Convert df to tensor ###

def get_device():
    if torch.cuda.is_available():
        device = torch.device('cuda:0')
    else:
        device = torch.device('cpu') # don't have GPU 
    return device

# convert a df to tensor to be used in pytorch
def df_to_tensor(elecs_to_nr):
    device = get_device()
    return torch.from_numpy(elecs_to_nr.values).float().to(device)

elecs_to_tensor = df_to_tensor(elecs_to_nr)
# series_tensor = df_to_tensor(series)
print(elecs_to_tensor[0:10])
print(elecs_to_tensor[0:10].shape)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]])
torch.Siz

### Raw data

In [120]:

## save raw_data in a list ##
#with append() in order to save lists of lists
raw_data_to_matrix=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                raw_data_to_matrix.append(pData[f'_{elec_i}_{muscle_i}'].Raw[trial])
               
print(len(raw_data_to_matrix))
print((raw_data_to_matrix[0])) #float64
# print((raw_data_to_matrix[0:10].dtype)) #error

raw_data_to_df = pd.DataFrame(raw_data_to_matrix) #convert to a pandas df
if len(raw_data_to_df.iloc[0])!=len((raw_data_to_matrix[0])): #get rid of nan column
    raw_data_to_df=raw_data_to_df.iloc[: , :-1]

16410
[-0.00460883 -0.00420606 -0.00464878 ...  0.96574819  1.05082721
  0.90098246]


In [121]:
#### Convert df to tensor ###

def get_device():
    if torch.cuda.is_available():
        device = torch.device('cuda:0')
    else:
        device = torch.device('cpu') # don't have GPU 
    return device

# convert a df to tensor to be used in pytorch
def df_to_tensor(raw_data_to_df):
    device = get_device()
    return torch.from_numpy(raw_data_to_df.values).float().to(device)

raw_data_to_tensor = df_to_tensor(raw_data_to_df)
# series_tensor = df_to_tensor(series)
print(raw_data_to_tensor[0:10])
print(raw_data_to_tensor.size())

tensor([[-0.0046, -0.0042, -0.0046,  ...,  0.9657,  1.0508,  0.9010],
        [ 0.0025,  0.0037,  0.0044,  ...,  0.9657,  1.0508,  0.9010],
        [ 0.0144,  0.0138,  0.0112,  ...,  0.9657,  1.0508,  0.9010],
        ...,
        [-0.0141, -0.0155, -0.0154,  ...,  0.9657,  1.0508,  0.9010],
        [-0.0111, -0.0113, -0.0112,  ...,  0.9657,  1.0508,  0.9010],
        [-0.0243, -0.0231, -0.0201,  ...,  0.9657,  1.0508,  0.9010]])
torch.Size([16410, 1403])


# Make a tensor with dimension (nElec, nMuscles, uniqeAmp, TPperTrial)

1. modify table: remove trig, make sure same amount of amp per muscle
2. reshape?

In [122]:
device =  "cuda" if torch.cuda.is_available() else "cpu"

Remvove unecessary

In [123]:
#check which values are available in muscle and remove uncesessary ones, eg trig
print(pData["_0_0"].List_muscle_or_other) 
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
        pData[f'_{elec_i}_{muscle_i}'].List_muscle_or_other= ['LST', 'RST', 'LTA', 'LMG', 'LSol', 'LVLat', 'LRF', 'LIl', 'RSol', 'RMG', 'RTA', 'RVLat', 'RRF', 'RIl']    


['LST' 'RST' 'LTA' 'LMG' 'LSol' 'LVLat' 'LRF' 'LIl' 'RSol' 'RMG' 'RTA'
 'RVLat' 'RRF' 'RIl' 'Trig']


In [124]:
#remove uncesessary Elecs ones for now only the monopolar ones necessary
print(pData["_0_0"].List_elecs) 
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
        pData[f'_{elec_i}_{muscle_i}'].List_elecs=['Elec01_', 'Elec02_', 'Elec03_', 'Elec04_', 'Elec05_', 'Elec06_', 'Elec07_', 'Elec08_', 'Elec09_', 'Elec10_', 'Elec11_', 'Elec12_', 'Elec13_', 'Elec14_', 'Elec15_', 'Elec16_']

['Elec01_' 'Elec02_' 'Elec03_' 'Elec04_' 'Elec05_' 'Elec06_' 'Elec07_'
 'Elec08_' 'Elec09_' 'Elec10_' 'Elec11_' 'Elec12_' 'Elec13_' 'Elec14_'
 'Elec15_' 'Elec16_' 'Elec13_09101214' 'Elec14_10' 'Elec04_0305'
 'Elec02_03']


In [172]:
## n_Ampl_unique
## find all the amplitudes used(unique); to have one dim of amplitudes, where there is no trial for an amplitude, fill with nan

unique_amplitudes=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
            for trial in pData[f'_{elec_i}_{muscle_i}'].Trial_number: #loop through the trials
                unique_amplitudes.append(pData[f'_{elec_i}_{muscle_i}'].Amplitudes[trial])


# mylist = list(set(mylist))
unique_amplitudes=np.unique(unique_amplitudes)  
print(unique_amplitudes)          



[0.5 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3
 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7]


In [227]:
## n_duplicates_per_amp
## find the max nr of trials for a same amplitude; we add a dimension with nr of trials with the same amplitude, where there is no data, we fill with nan

trials_same_amp=[]
for elec_i in range (len(pData["_0_0"].List_elecs)) : #loop through all the elecs
    for muscle_i in range (len(pData["_0_0"].List_muscle_or_other)): # loop through all the muscles
        trials_same_amp.append(np.max(pd.Index(pData[f'_{elec_i}_{muscle_i}'].Amplitudes).value_counts())) #extract the max nr of repeated amp in one combination
       
max_trials_same_amp=np.max(trials_same_amp)



Create tensor

In [328]:
### Create tensor with size torch.Size([16, 14, 32, 11, 1403]) 
# nMuslces x nElecs x nAmp_unique x n_duplicates_per_amp x raw_data_per trial
all_data_to_tensor=torch.ones(len(pData["_0_0"].List_elecs),len(pData["_0_0"].List_muscle_or_other),len(unique_amplitudes),max_trials_same_amp,int(pData["_0_0"].Time_points[pData["_0_0"].Trial_number[0]]))
all_data_to_tensor.size()

torch.Size([16, 14, 32, 11, 1403])

fill up just for elec 0, muslce 0

In [326]:
## Starting with elec 0, muslce 0, amp=0.5, filling the 10rows (repetition) for the spec. amp with the raw data/ resp nan value since there is no data for that amplitude

ind=0 # set index to zero, will serve as index in the amplitudes
for pos_in_unique_amplitudes in range(len(unique_amplitudes)): #loop through all the amplitudes possible
    trial=pData["_0_0"].Amplitudes.index[ind]
    print(f"Amplitude of unique amp:{unique_amplitudes[pos_in_unique_amplitudes]}, Trial_nr:{trial}")

    if pData["_0_0"].Amplitudes[trial] > unique_amplitudes[pos_in_unique_amplitudes]:
        print(f"Data for Amplitude {pData['_0_0'].Amplitudes[trial]} too high for {unique_amplitudes[pos_in_unique_amplitudes]}, fill all the repeats with nan for this amplitude")
        all_data_to_tensor[0, 0, pos_in_unique_amplitudes, :, :]=torch.zeros((11, 1403)).float()
        all_data_to_tensor[all_data_to_tensor==0]= float('nan') #didn't find torch.nan function
           
    elif pData["_0_0"].Amplitudes[trial] == unique_amplitudes[pos_in_unique_amplitudes]:
        print("same amplitude")
        reps_for_amp=pd.Index(pData["_0_0"].Amplitudes).value_counts(sort=False)[pData["_0_0"].Amplitudes[trial]] #outputs the repeats of trials for the spec amplitude
        
        if reps_for_amp < max_trials_same_amp:
        ##fill everything with nan values
            all_data_to_tensor[0, 0, pos_in_unique_amplitudes, :, :]=torch.zeros((11, 1403)).float()
            all_data_to_tensor[all_data_to_tensor==0]= float('nan') #didn't find torch.nan function

            #save the trials with data
        for repeats in range(reps_for_amp):
            trial=pData["_0_0"].Amplitudes.index[ind]
            all_data_to_tensor[0, 0, pos_in_unique_amplitudes,repeats,:]=torch.Tensor(pData["_0_0"].Raw[trial])
            ind+=1
            print(all_data_to_tensor[0, 0, pos_in_unique_amplitudes,repeats,:])
       


Amplitude of unique amp:0.5, Trial_nr:27
Data for Amplitude 1.5 too high for 0.5, fill all the repeats with nan for this amplitude
Amplitude of unique amp:0.7, Trial_nr:27
Data for Amplitude 1.5 too high for 0.7, fill all the repeats with nan for this amplitude
Amplitude of unique amp:0.8, Trial_nr:27
Data for Amplitude 1.5 too high for 0.8, fill all the repeats with nan for this amplitude
Amplitude of unique amp:0.9, Trial_nr:27
Data for Amplitude 1.5 too high for 0.9, fill all the repeats with nan for this amplitude
Amplitude of unique amp:1.0, Trial_nr:27
Data for Amplitude 1.5 too high for 1.0, fill all the repeats with nan for this amplitude
Amplitude of unique amp:1.1, Trial_nr:27
Data for Amplitude 1.5 too high for 1.1, fill all the repeats with nan for this amplitude
Amplitude of unique amp:1.2, Trial_nr:27
Data for Amplitude 1.5 too high for 1.2, fill all the repeats with nan for this amplitude
Amplitude of unique amp:1.3, Trial_nr:27
Data for Amplitude 1.5 too high for 1.3, f

In [327]:

print(all_data_to_tensor)

tensor([[[[[        nan,         nan,         nan,  ...,         nan,
                    nan,         nan],
           [        nan,         nan,         nan,  ...,         nan,
                    nan,         nan],
           [        nan,         nan,         nan,  ...,         nan,
                    nan,         nan],
           ...,
           [        nan,         nan,         nan,  ...,         nan,
                    nan,         nan],
           [        nan,         nan,         nan,  ...,         nan,
                    nan,         nan],
           [        nan,         nan,         nan,  ...,         nan,
                    nan,         nan]],

          [[        nan,         nan,         nan,  ...,         nan,
                    nan,         nan],
           [        nan,         nan,         nan,  ...,         nan,
                    nan,         nan],
           [        nan,         nan,         nan,  ...,         nan,
                    nan,         nan],
 

In [236]:
if pData["_0_0"].Amplitudes[trial] > unique_amplitudes[0]:
    print("Data for higher ampplitudes, fill all the repeats with nan for this amplitude")
    all_data_to_tensor[0, 0, 0, :, :]=torch.zeros((11, 1403)).float()
    all_data_to_tensor[all_data_to_tensor==0]= float('nan')
print(all_data_to_tensor)

Data for higher ampplitudes, fill all the repeats with nan for this amplitude
tensor([[[[[nan, nan, nan,  ..., nan, nan, nan],
           [nan, nan, nan,  ..., nan, nan, nan],
           [nan, nan, nan,  ..., nan, nan, nan],
           ...,
           [nan, nan, nan,  ..., nan, nan, nan],
           [nan, nan, nan,  ..., nan, nan, nan],
           [nan, nan, nan,  ..., nan, nan, nan]],

          [[1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           ...,
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.]],

          [[1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           ...,
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.],
           [1., 1., 1.,  ..., 1., 1., 1.]],

          ...,

          [[1., 1., 1.,  ..., 1., 1., 1.],

# Save the data as a pickle file